name: XXQG

# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * 1'
    # 表达式生成  https://crontab.guru/
    #- cron: '0 */3 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2
    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: 加载缓存
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r ./XXQG_TiKu/requirements.txt
    - name: 执行任务1
      run: |
        python ./XXQG_TiKu/json_to_question.py
    - name: 执行任务2
      run: |
        python ./XXQG_TiKu/json_to_sql.py
    - name: 提交更改
      run: |
        git config --local user.email '${{ secrets.EMAIL }}'
        git config --local user.name '${{ secrets.NAME }}'
        git pull origin main
        git add ./XXQG_TiKu/question
        git add ./XXQG_TiKu/QuestionBank.db
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S')"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        branch: main
      
